// src/services/location/vietnam-provinces.ts
export type Province = {
  name: string;
  code: number;
};

export const vietnamProvinces: Province[] = [
  { name: "Hà Nội", code: 1 },
  { name: "Hồ Chí Minh", code: 79 },
  { name: "Đà Nẵng", code: 48 },
  { name: "Hải Phòng", code: 31 },
  { name: "Cần Thơ", code: 92 },
  { name: "An Giang", code: 89 },
  { name: "Bà Rịa - Vũng Tàu", code: 77 },
  { name: "Bắc Giang", code: 24 },
  { name: "Bắc Kạn", code: 6 },
  { name: "Bạc Liêu", code: 95 },
  { name: "Bắc Ninh", code: 27 },
  { name: "Bến Tre", code: 83 },
  { name: "Bình Định", code: 52 },
  { name: "Bình Dương", code: 74 },
  { name: "Bình Phước", code: 70 },
  { name: "Bình Thuận", code: 60 },
  { name: "Cà Mau", code: 96 },
  { name: "Cao Bằng", code: 4 },
  { name: "Đắk Lắk", code: 66 },
  { name: "Đắk Nông", code: 67 },
  { name: "Điện Biên", code: 11 },
  { name: "Đồng Nai", code: 75 },
  { name: "Đồng Tháp", code: 87 },
  { name: "Gia Lai", code: 64 },
  { name: "Hà Giang", code: 2 },
  { name: "Hà Nam", code: 35 },
  { name: "Hà Tĩnh", code: 42 },
  { name: "Hải Dương", code: 30 },
  { name: "Hậu Giang", code: 93 },
  { name: "Hòa Bình", code: 17 },
  { name: "Hưng Yên", code: 33 },
  { name: "Khánh Hòa", code: 56 },
  { name: "Kiên Giang", code: 91 },
  { name: "Kon Tum", code: 62 },
  { name: "Lai Châu", code: 12 },
  { name: "Lâm Đồng", code: 68 },
  { name: "Lạng Sơn", code: 20 },
  { name: "Lào Cai", code: 10 },
  { name: "Long An", code: 80 },
  { name: "Nam Định", code: 36 },
  { name: "Nghệ An", code: 40 },
  { name: "Ninh Bình", code: 37 },
  { name: "Ninh Thuận", code: 58 },
  { name: "Phú Thọ", code: 25 },
  { name: "Phú Yên", code: 54 },
  { name: "Quảng Bình", code: 44 },
  { name: "Quảng Nam", code: 49 },
  { name: "Quảng Ngãi", code: 51 },
  { name: "Quảng Ninh", code: 22 },
  { name: "Quảng Trị", code: 45 },
  { name: "Sóc Trăng", code: 94 },
  { name: "Sơn La", code: 14 },
  { name: "Tây Ninh", code: 72 },
  { name: "Thái Bình", code: 34 },
  { name: "Thái Nguyên", code: 19 },
  { name: "Thanh Hóa", code: 38 },
  { name: "Thừa Thiên Huế", code: 46 },
  { name: "Tiền Giang", code: 82 },
  { name: "Trà Vinh", code: 84 },
  { name: "Tuyên Quang", code: 8 },
  { name: "Vĩnh Long", code: 86 },
  { name: "Vĩnh Phúc", code: 26 },
  { name: "Yên Bái", code: 15 },
];

// Sắp xếp A-Z
vietnamProvinces.sort((a, b) => a.name.localeCompare(b.name));
